"""ComponentTemplate - Composition-based Dash component templates.

Architecture:
- LazyComponent: Base class with all runtime logic
- Factory creates LazyComponent subclasses dynamically
- Stubs provide typing for dynamically created classes

Design principles:
- Template base class with tree composition
- Clean separation: tree vs component logic
- Proxy pattern for tree access
- Pure component namespace

Key Features:
- Composes IdTree (not inherits) for clean separation
- Props namespace for all Dash properties
- Two-stage API: setup + materialize
- Typed child templates via .child[Type](...)
- Natural tree manipulation via proxies
"""

from __future__ import annotations

import functools
from typing import TYPE_CHECKING, Any, ClassVar

from .naming import (
    get_component_id_stem,
    get_lazy_component_cls_name,
    get_template_cls_name,
)
from .props_namespace import _PropsNamespace
from .template import Template, _Template
from .template_idtree import TemplateIdTree

if TYPE_CHECKING:
    from dash.development.base_component import Component

    from .component_info import DashComponentInfo

__all__ = [
    "LazyComponent",
]


class _LazyComponentIdTree(TemplateIdTree):
    """IdTree for LazyComponent that uses component class name for id_stem."""

    def _id_stem(self) -> str:
        """Get ID stem from component class name.

        Uses centralized naming utility for consistent ID generation.
        Returns concise stem like 'div' for html.Div or 'button' for dmc.Button.
        Falls back to class name for base LazyComponent instances.
        """
        from .lazy_component import LazyComponent

        owner = self._owner
        assert isinstance(owner, LazyComponent), (
            f"Owner must be LazyComponent, got {type(owner)}"
        )

        # Factory-created subclasses have _component_cls set
        if owner._component_cls is not None:
            return get_component_id_stem(owner._component_cls)

        # Base LazyComponent instance (test-only case) - fallback to class name
        return super()._id_stem()


@functools.cache
def _make_lazy_component_cls(
    component_cls: type[Component],
) -> type[LazyComponent]:
    """Create or retrieve cached LazyComponent subclass for component_cls.

    This dynamically creates a non-generic runtime subclass like:

    ```python
    class LazyComponentHtmlDiv(LazyComponent):
        _component_cls = html.Div
        _dash_component_info = DashComponentInfo(...)
    ```

    The factory creates LazyComponent subclasses dynamically.
    Type information is provided via stub files for full IDE support.

    The subclass is fully typed and chainable. Properties are accessed via
    the .props._PropsNamespace, with full IDE autocomplete provided by
    stub files (.pyi) that define typed property attributes.

    Results are cached using functools.lru_cache(maxsize=None) for performance.
    The same subclass is returned for repeated calls with the same component_cls.

    Parameters
    ----------
    component_cls : type[Component]
        Dash component class (e.g., html.Div, dmc.Button)

    Returns
    -------
    type[LazyComponent]
        LazyComponent subclass specialized for component_cls

    Examples
    --------
    Internal use (for framework code):
    >>> from dash import html
    >>> DivTemplate = _make_lazy_component_cls(html.Div)
    >>> div = DivTemplate(className="container")

    Recommended user pattern:
    >>> from dash_component_template import Template
    >>> template = Template()
    >>> div = template.child[html.Div](className="container")

    Notes
    -----
    Creates specialized LazyComponent subclasses dynamically.
    Type information comes from stub files for IDE autocomplete.

    Caching is handled by functools.lru_cache decorator.
    """
    # Generate class name using naming utilities
    # E.g., html.Div -> LazyComponentHtmlDiv (matches stub file naming)
    class_name = get_lazy_component_cls_name(component_cls)

    # Create LazyComponent subclass dynamically
    # Note: __init_subclass__ will be called automatically and will
    # auto-generate _dash_component_info from _component_cls
    component_name = component_cls.__name__

    # Create non-generic LazyComponent subclass for runtime efficiency
    return type(
        class_name,
        (LazyComponent,),
        {
            # Class variables
            "_component_cls": component_cls,
            # _dash_component_info will be auto-generated by __init_subclass__
            # Module for better debugging
            "__module__": __name__,
            # Docstring for IDE help
            "__doc__": (
                f"LazyComponent for {component_cls.__module__}.{component_name}.\n\n"
                f"This is a dynamically generated non-generic subclass. Access properties \n"  # noqa: E501
                f"via .props with full IDE autocomplete (provided by stub files).\n\n"
                f"The subclass is fully chainable - use .child[...] to add children."
            ),
        },
    )


class _LazyComponentFactory:
    """Factory for creating child LazyComponent instances via .child[Type](...) syntax."""  # noqa: E501

    def __init__(self, owner: _Template | None = None) -> None:
        """Initialize factory with optional owner template.

        Parameters
        ----------
        owner : _Template | None
            Parent template that will own created children.
            If None, creates root templates without parent.
        """
        self._owner = owner

    def __call__(self, item: Component | _Template) -> _Template:
        """Add existing component or template as child.

        This method supports two patterns:
        1. Wrapping a Dash component instance in a WrappedComponent template
        2. Adding an existing template as a child (sets parent)

        Parameters
        ----------
        item : Component | _Template
            Either a Dash component instance to wrap, or an existing
            template to add as a child.

        Returns
        -------
        _Template
            For components: returns WrappedComponent with item as the component.
            For templates: returns the same template with parent set.

        Examples
        --------
        Wrap a component instance:

        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> wrapped = root.child(html.Div("Hello", className="box"))
        >>> wrapped.parent is root
        True

        Add existing template:

        >>> root = Template()
        >>> header = Template()
        >>> added = root.child(header)
        >>> added is header
        True
        >>> header.parent is root
        True
        """
        from dash.development.base_component import Component

        from .wrapped_component import WrappedComponent

        # Check if it's a template (has the _Template interface)
        if isinstance(item, _Template):
            # Simply add template as child by setting its parent
            # No tree manipulations during construction - that happens in setup_layout()
            item.parent = self._owner
            return item

        # Check if it's a Dash Component instance
        if isinstance(item, Component):
            return WrappedComponent(item, _parent=self._owner)

        # Neither template nor component - raise TypeError
        msg = (
            f"_LazyComponentFactory can only accept _Template or Component instances, "
            f"got {type(item).__name__}. "
            f"Use template.child[ComponentClass](...) for creating new components."
        )
        raise TypeError(
            msg,
        )

    def __getitem__(self, component_cls: type[Component]) -> type[LazyComponent]:
        """Get factory function for component type.

        This method:
        1. Looks up (or creates) the LazyComponent subclass for component_cls
        2. Returns functools.partial with _parent bound to self._owner (or None)

        Parameters
        ----------
        component_cls : type[Component]
            Dash component class (e.g., html.Div, dmc.Button)

        Returns
        -------
        type[LazyComponent]
            LazyComponent class with _parent pre-bound via functools.partial.
            Type checkers see this as the full LazyComponent class, enabling
            IDE autocomplete for all component properties from stub files.

        Notes
        -----
        At runtime, this returns functools.partial(LazyComponent, _parent=self._owner).
        For type checking, stub files provide overloads that map each component
        class to its corresponding stub class (e.g., html.Div -> LazyComponentHtmlDiv).

        Examples
        --------
        With parent:

        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> btn = root.child[html.Button](children='Click me')
        >>> btn.parent == root
        True
        """
        # Get or create the template class using shared registry
        template_cls = _make_lazy_component_cls(component_cls)

        # Return partial with parent pre-bound (may be None for root templates)
        # Type checker sees specific stub class from overloads in component_template.pyi
        return functools.partial(template_cls, _parent=self._owner)  # type: ignore[return-value]


class LazyComponent(_Template):
    """Non-generic base with all runtime behavior.

    This is the runtime implementation for component templates.
    It provides all the actual component template logic that gets executed.

    LazyComponent represents a Dash component before it's created (materialized).
    It allows building component trees, setting properties, and creating actual
    Dash components on demand.

    The template uses composition (not inheritance) for tree structure, keeping
    the namespace clean for Dash properties.

    IMPORTANT: Users should NOT directly instantiate LazyComponent.
    Instead, users should:
    - Subclass Template for custom layout logic
    - Use Template's .child[Component]() factory to create component templates

    LazyComponent instances are created automatically by the factory.

    Class Attributes
    ----------------
    _component_cls : type[Component] or None
        Dash component class to materialize (e.g., html.Div)

    Private Attributes
    ------------------
    _dash_component_info : DashComponentInfo or None
        Metadata about component properties (auto-generated from _component_cls)

    Examples
    --------
    Create typed templates via .child[] factory (recommended):

    >>> from dash_component_template import Template
    >>> from dash import html
    >>> template = Template()
    >>> div = template.child[html.Div](className="container")
    >>> div.props.className = "updated"
    >>> component = div.materialize()

    Build component trees:

    >>> template = Template()
    >>> parent = template.child[html.Div]()
    >>> child = parent.child[html.Div](children="Hello")
    >>> child.parent is parent
    True
    >>> component = parent.materialize()
    >>> component.id == parent.id
    True

    Notes
    -----
    LazyComponent subclasses created by the factory have _component_cls set.
    Use the .child[Type]() factory pattern for creating component templates.
    """

    # Use custom IdTree that gets id_stem from component class name
    _idtree_cls = _LazyComponentIdTree

    # Class variables for Dash component integration
    # NOTE: Factory-created subclasses MUST set _component_cls
    _component_cls: ClassVar[type[Component] | None] = None
    _dash_component_info: ClassVar[DashComponentInfo | None] = None

    def __init_subclass__(cls, **kwargs) -> None:
        """Auto-generate component info from _component_cls.

        For LazyComponent subclasses created by the factory,
        this auto-generates _dash_component_info from the provided _component_cls.

        All properties are accessed via the .props namespace.
        """
        super().__init_subclass__(**kwargs)

        # Auto-generate _dash_component_info from _component_cls
        # Factory-created subclasses MUST have _component_cls set
        # Base LazyComponent class is exempt (used only for isinstance checks)
        if cls is not LazyComponent:
            if cls._component_cls is None:
                msg = (
                    f"LazyComponent subclass {cls.__name__} must have _component_cls set. "  # noqa: E501
                    f"Use _make_lazy_component_cls() factory to create subclasses."
                )
                raise TypeError(
                    msg,
                )
            from .component_info import get_component_info

            cls._dash_component_info = get_component_info(cls._component_cls)

    def __init__(
        self,
        *args,
        _parent: Template | None = None,
        **kwargs,
    ) -> None:
        """Initialize ComponentTemplate with composition.

        Sets up tree node via Template.__init__ and creates props namespace.
        Positional arguments are mapped to property names based on the order
        defined in the component's __init__ signature (dash_component_info.prop_names).

        Parameters
        ----------
        *args : Any
            Positional arguments mapped to component properties by prop_names order
        _parent : Template, optional
            Parent template for tree hierarchy (internal parameter)
        **kwargs : Any
            Keyword arguments for component properties

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> # Using keyword args
        >>> div = root.child[html.Div](className="test", style={"color": "blue"})
        >>> div.props.className
        'test'
        >>> # Using positional args (e.g., prop_names = ['children', 'id', ...])
        >>> div2 = root.child[html.Div]("Hello", "my-id", "test-class")
        >>> div2.props.children
        'Hello'

        Notes
        -----
        Positional args are mapped by iterating prop_names from dash_component_info.
        If both positional and keyword args are provided for the same property,
        keyword args take precedence.
        """
        # Initialize tree via Template.__init__
        super().__init__(_parent=_parent)

        # Merge positional args with kwargs based on prop_names order
        merged_props = {}
        if args and self._dash_component_info is not None:
            # Map positional args to prop_names
            prop_names = self._dash_component_info.prop_names
            for i, value in enumerate(args):
                if i < len(prop_names):
                    merged_props[prop_names[i]] = value

        # Keyword args override positional args
        merged_props.update(kwargs)

        # Create props namespace with merged properties
        self._props = _PropsNamespace(**merged_props)

    @property
    def props(self) -> _PropsNamespace:
        """Access Dash component properties.

        Returns the props namespace that isolates all Dash properties from
        user attributes. Supports both attribute and dict-style access.

        Returns
        -------
        _PropsNamespace
            Namespace for accessing Dash component properties

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div]()
        >>> div.props.className = "container"
        >>> div.props["data-testid"] = "my-component"
        >>> div.props_update({"style": {"padding": "10px"}})
        """
        return self._props

    def props_dict(self) -> dict[str, Any]:
        """Get all properties as a plain dict.

        Returns a shallow copy of the internal props dict. This is useful
        for inspection, debugging, or passing to other functions.

        Returns
        -------
        dict[str, Any]
            Dictionary of all set properties (including None values)

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div]()
        >>> div.props.className = "test"
        >>> div.props_dict()
        {'className': 'test'}
        """
        return dict(self._props._data)

    def props_update(self, props: dict[str, Any]) -> None:
        """Update multiple properties at once.

        Parameters
        ----------
        props : dict[str, Any]
            Properties to update

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div]()
        >>> div.props_update({"className": "test", "style": {"color": "red"}})
        """
        for key, value in props.items():
            self._props[key] = value

    def __repr__(self) -> str:
        """Return string representation showing component type and ID.

        Returns
        -------
        str
            Format: ClassName(id='template-id', namespace.ComponentName)

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div]()
        >>> repr(div)  # doctest: +ELLIPSIS
        "LazyComponentHtmlDiv(id='template...', html.Div)"
        """
        if self._component_cls is None:
            # Base LazyComponent instance (test-only case)
            return f"{self.__class__.__name__}(id='{self.id}')"

        # Use naming utilities for consistent component identification
        from .naming import get_component_cls_slug

        slug = get_component_cls_slug(self._component_cls)
        return f"{self.__class__.__name__}(id='{self.id}', {slug})"

    def props_rupdate(self, props: dict[str, Any]) -> None:
        """Update properties with recursive deep merge.

        For nested dicts, merges recursively instead of replacing.
        Useful for updating nested style or other nested properties.

        Parameters
        ----------
        props : dict[str, Any]
            Properties to update (deep merge)

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div]()
        >>> div.props.style = {"padding": "10px"}
        >>> div.props_rupdate({"style": {"margin": "5px"}})
        >>> div.props.style
        {'padding': '10px', 'margin': '5px'}
        """
        from .props_namespace import _deep_merge

        _deep_merge(self._props._data, props)

    @property
    def materialized(self) -> Component:  # type: ignore[override]
        """Get the materialized Dash component.

        LazyComponent override that returns the single component (not a list).
        This is the primary way to access component IDs in callbacks.

        Returns
        -------
        Component
            The materialized Dash component

        Raises
        ------
        ValueError
            If materialize() has not been called yet

        Examples
        --------
        >>> from dash import html, Input, Output
        >>> from dash_component_template import Template
        >>> class MyTemplate(Template):
        ...     def __init__(self):
        ...         super().__init__()
        ...         container = self.child[html.Div]()
        ...         self.button = container.child[html.Button](children="Click")
        ...         self.display = container.child[html.Div]()
        ...
        ...     def setup_callbacks(self, app):
        ...         @app.callback(
        ...             Output(self.display.materialized, "children"),
        ...             Input(self.button.materialized, "n_clicks")
        ...         )
        ...         def update(n):
        ...             return f"Clicked {n} times"

        Notes
        -----
        - Must call materialize() before accessing this property
        - Dash callback system extracts .id from components automatically
        - For pattern-matching, use the __call__ method instead
        - Overrides base _Template.materialized to return single Component
        """
        if self._materialized is None or len(self._materialized) == 0:
            msg = (
                f"Cannot access materialized component for '{self.id}': "
                f"materialize() has not been called yet. "
                f"Ensure you call template.layout() or template.materialize() "
                f"before registering callbacks."
            )
            raise ValueError(msg)
        return self._materialized[0]

    def _get_owning_template(self) -> Template | None:
        """Get the nearest Template ancestor of this LazyComponent.

        Walks up the tree to find the first ancestor whose owner is a
        ``Template`` instance (not a ``LazyComponent``). This is the template
        that *owns* this component and defines its callback scope.

        Returns
        -------
        Template or None
            The nearest Template ancestor, or None if this component has no
            Template ancestor (standalone use, such as in tests).

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> class MyWidget(Template):
        ...     def __init__(self):
        ...         super().__init__()
        ...         container = self.child[html.Div]()
        ...         self.btn = container.child[html.Button]()
        >>> w = MyWidget()
        >>> # Both direct child and deeper child resolve to the same owner
        >>> w.btn._get_owning_template() is w
        True
        """
        node = self._tree.parent
        while node is not None:
            owner = getattr(node, "_owner", None)
            if owner is not None and isinstance(owner, Template):
                return owner
            node = getattr(node, "parent", None)
        return None

    def _get_owning_template_id(self) -> str:
        """Get the ID of the nearest Template ancestor for scope isolation.

        All LazyComponent instances within the same Template share this ID as
        their ``_template_id``, which is essential for pattern-matching
        callbacks to correctly isolate different template instances.

        Returns
        -------
        str
            ID of the nearest Template ancestor, or ``self.id`` when this
            component has no Template ancestor (standalone use in tests).

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> class MyWidget(Template):
        ...     def __init__(self):
        ...         super().__init__()
        ...         self.btn = self.child[html.Button]()
        ...         self.label = self.child[html.Div]()
        >>> w = MyWidget()
        >>> # Both btn and label share the widget's ID as owning template ID
        >>> w.btn._get_owning_template_id() == w.id
        True
        >>> w.label._get_owning_template_id() == w.id
        True
        >>> w.btn._get_owning_template_id() == w.label._get_owning_template_id()
        True
        """
        owner = self._get_owning_template()
        return owner.id if owner is not None else self.id

    def _make_component_id(
        self, id_overrides: dict[str, Any] | None = None
    ) -> str | dict[str, Any]:
        """Create component ID with automatic scope injection.

        This is the single source of truth for ID creation. Used by both
        materialize() and __call__() to ensure consistent ID generation.

        Parameters
        ----------
        id_overrides : dict, optional
            Pattern-matching markers to merge into the component ID.
            If None, returns the base ID (string or dict from props).

        Returns
        -------
        str or dict[str, Any]
            - If no dict ID and no overrides: returns string ID
            - If dict ID in props: returns dict with scope injected
            - If overrides provided: returns merged dict with scope

        Raises
        ------
        TypeError
            If base component ID is not a string or dict.
        ValueError
            If base component ID is a string and pattern-matching is attempted.
        """
        # Dash Props objects implement __contains__ but not .get(); use "in" + subscript
        base_id = self._props["id"] if "id" in self._props else self.id  # noqa: SIM401

        # Validate base_id type - must be str or dict
        if not isinstance(base_id, (str, dict)):
            component_type = (
                self._component_cls.__name__ if self._component_cls else "Component"
            )
            msg = (
                f"Component ID must be a string or dict, got {type(base_id).__name__}: {base_id!r}. "  # noqa: E501
                f"For component {component_type}, provide either:\n"
                f"  - String ID: id='my-id'\n"
                f"  - Dict ID: id={{'type': 'my-type', 'index': 0}}"
            )
            raise TypeError(msg)

        # Handle type-specific logic
        if isinstance(base_id, str):
            # String ID - return as-is if no pattern-matching
            if id_overrides is None:
                return base_id

            # ERROR: Cannot pattern-match with string IDs
            component_type = (
                self._component_cls.__name__ if self._component_cls else "Component"
            )
            msg = (
                f"Cannot use pattern matching with string ID '{base_id}'. "
                f"To use pattern matching, provide a dict ID when creating the component:\n"  # noqa: E501
                f"  self.component = self.child[{component_type}](\n"
                f"    id={{'type': 'my_type', 'index': 0}},\n"
                f"    ...\n"
                f"  )\n"
                f"Then you can use pattern matching in callbacks:\n"
                f"  self.component({{'index': MATCH}})"
            )
            raise ValueError(msg)

        # Dict ID - merge with defaults, overrides, and scope
        # Start with a copy of the base dict ID
        merged_id: dict[str, Any] = dict(base_id)

        # Set default scope metadata using the owning Template.
        # Both _template_name and _template_id are derived from the nearest
        # Template ancestor (not this LazyComponent's own class/id). This
        # ensures all components within one Template instance share the same
        # scope keys, which is required for pattern-matching callbacks to
        # correctly pair inputs/outputs and isolate different instances.
        owning = self._get_owning_template()
        if owning is not None:
            merged_id.setdefault("_template_name", get_template_cls_name(type(owning)))
            merged_id.setdefault("_template_id", owning.id)
        else:
            # Standalone component (tests, no parent Template)
            merged_id.setdefault(
                "_template_name", get_template_cls_name(self.__class__)
            )
            merged_id.setdefault("_template_id", self.id)

        # Merge user overrides if provided
        if id_overrides is not None:
            merged_id.update(id_overrides)

        # Get current callback scope and let it override everything
        from .template import _get_current_scope

        scope = _get_current_scope()
        merged_id.update(scope)

        return merged_id

    def __call__(
        self, id_overrides: dict[str, Any] | None = None
    ) -> Component | dict[str, Any]:
        """Get component for callbacks with optional pattern-matching ID overrides.

        This is the primary method for accessing components in callbacks.

        - `self.button()` returns the materialized component
        - `self.button({"index": MATCH})` returns a dict ID for pattern-matching

        When id_overrides are provided, returns a dict ID that merges:
        1. Base component ID (string converted to {"id": base_id} or dict copied)
        2. User's pattern-matching overrides (type, index, MATCH, ALL, etc.)
        3. Automatic scope metadata (_template_name, _template_id)

        The scope metadata ensures pattern-matching callbacks filter by template:
        - Instance-scoped (default): _template_id matches this specific instance
        - Class-scoped: Use callback_scope(template_id=MATCH) to match all instances
        - Global-scoped: Use callback_scope(template_name=MATCH, template_id=MATCH)

        Parameters
        ----------
        id_overrides : dict, optional
            Pattern-matching markers to merge into the component ID.
            Common values: MATCH, ALL, ALLSMALLER from dash.dependencies

        Returns
        -------
        Component or dict[str, Any]
            If id_overrides is None: returns the materialized component
            If id_overrides given: returns dict ID with automatic scope injection

        Raises
        ------
        ValueError
            If base component ID is a string and pattern-matching is attempted.
            User must provide dict ID explicitly for pattern-matching.

        Examples
        --------
        Simple callback (no pattern-matching):

        >>> from dash import Input, Output
        >>> def setup_callbacks(self, app):
        ...     @app.callback(
        ...         Output(self.display(), "children"),
        ...         Input(self.button(), "n_clicks")
        ...     )
        ...     def update(n):
        ...         return f"Clicked {n} times"

        Pattern-matching callback (requires explicit dict ID in layout):

        >>> from dash import MATCH
        >>> # In __init__:
        >>> self.button = self.child[html.Button](
        ...     id={"type": "btn", "index": 0},  # Explicit dict ID
        ...     children="Click"
        ... )
        >>> # In setup_callbacks:
        >>> def setup_callbacks(self, app):
        ...     @app.callback(
        ...         Output(self.display({"index": MATCH}), "children"),
        ...         Input(self.button({"index": MATCH}), "n_clicks")
        ...     )
        ...     def update(n):
        ...         return f"Clicked {n} times"

        The __call__ method automatically includes:
        - _template_name: "MyTemplate" (from self.__class__.__name__)
        - _template_id: "MyTemplate_0" (from self.id)

        Ensuring the callback only matches components from this template instance.

        Pattern-matching callback (class-scoped for all instances):

        >>> from dash import MATCH
        >>> from dash_component_template import callback_scope
        >>> @classmethod
        >>> def setup_class_callbacks(cls, app):
        ...     # Get first instance for accessing component structure
        ...     first = cls._get_instances()[0]
        ...     # Override scope to match all instances
        ...     with callback_scope(template_id=MATCH):
        ...         @app.callback(
        ...             Output(first.display({"index": MATCH}), "children"),
        ...             Input(first.button({"index": MATCH}), "n_clicks")
        ...         )
        ...         def update_all_instances(n):
        ...             return f"Clicked {n} times (any instance)"

        Cross-template callback (global scope):

        >>> with callback_scope(template_name=MATCH, template_id=MATCH):
        ...     @app.callback(
        ...         Output("summary", "children"),
        ...         Input(first.button({"index": ALL}), "n_clicks")
        ...     )
        ...     def aggregate_all(all_clicks):
        ...         return f"Total: {sum(c for c in all_clicks if c)}"

        Notes
        -----
        - Pattern-matching REQUIRES dict IDs in the component definition
        - Cannot auto-convert string IDs to dicts (breaks Dash ID matching)
        - Scope metadata is auto-injected from callback_scope or defaults
        - User overrides take precedence over base_id keys
        - Scope keys are merged last to ensure proper scoping
        - Works correctly with nested templates (each has its own scope in the stack)
        """
        # Get the materialized component first
        component = self.materialized

        # If no overrides, return the component directly
        if id_overrides is None:
            return component

        # Use centralized ID creation logic
        # Type assertion: _make_component_id with overrides always returns dict
        return self._make_component_id(id_overrides)  # type: ignore[return-value]

    def materialize(self) -> list[Component]:
        """Create actual Dash component from template.

        Recursively materializes all child templates and creates the component
        tree (props from props_dict(), children from Template.children).

        Returns
        -------
        list[Component]
            List with single materialized Dash component

        Raises
        ------
        TypeError
            If _component_cls is not set (cannot materialize without component type)

        Examples
        --------
        >>> from dash import html
        >>> from dash_component_template import Template
        >>> root = Template()
        >>> div = root.child[html.Div](className="test")
        >>> btn = div.child[html.Button](children="Click")
        >>> components = div.materialize()
        >>> len(components)
        1
        >>> components[0].className
        'test'
        >>> len(components[0].children)
        1

        Notes
        -----
        All templates must have _component_cls set to materialize.
        Use the .child[] factory to create properly typed templates.

        Creates fresh components on each call (not idempotent).
        """
        # Assert invariants for type narrowing (subclasses only)
        if self._component_cls is None:
            msg = (
                f"Cannot materialize template '{self.id}': _component_cls is not set. "
                f"Use Template().child[ComponentClass]() to create properly typed templates."  # noqa: E501
            )
            raise TypeError(
                msg,
            )

        assert self._dash_component_info is not None, (
            f"Cannot materialize template '{self.id}': _dash_component_info not set. "
            f"Should be auto-generated in __init_subclass__."
        )

        # Get all props from props_dict (filters None values)
        all_props = self.props_dict()

        # Use centralized ID creation logic (single source of truth)
        # This ensures consistent ID generation between materialize() and __call__()
        if "id" in self._dash_component_info.prop_names:
            all_props["id"] = self._make_component_id()

        # Early return if component doesn't support children
        if "children" not in self._dash_component_info.prop_names:
            if self.children:
                import warnings

                warnings.warn(
                    f"Component {self._component_cls.__name__} does not support 'children' property, "  # noqa: E501
                    f"but template '{self.id}' has {len(self.children)} child templates. "  # noqa: E501
                    f"Children will be ignored.",
                    UserWarning,
                    stacklevel=2,
                )
            # Create component without children, return as list
            component = self._component_cls(**all_props)
            self._materialized = [component]
            return self._materialized

        # Reuse base class recursion logic to materialize children
        child_components = super().materialize()

        # Merge children from props and materialized templates
        props_children = all_props.get("children")

        if props_children is not None:
            # Props children take precedence, append our children
            if isinstance(props_children, list):
                all_children = props_children + child_components
            else:
                all_children = [props_children, *child_components]
        else:
            all_children = child_components or None

        # Set children if we have any
        if all_children:
            all_props["children"] = all_children

        # Create component and return as list
        component = self._component_cls(**all_props)
        self._materialized = [component]
        return self._materialized

    def callbacks(self, app: Any) -> None:
        """Register callbacks with Dash app (extension point).

        This is a hook for subclasses to register callbacks.
        The default implementation does nothing.

        Parameters
        ----------
        app : dash.Dash
            Dash application instance

        Examples
        --------
        >>> class MyTemplate(ComponentTemplate):  # doctest: +SKIP
        ...     def callbacks(self, app):
        ...         @app.callback(Output('output', 'children'), Input('input', 'value'))
        ...         def my_callback(value):
        ...             return value
        """

    def register(self, app: Any) -> None:
        """Recursively register callbacks for this template and all children.

        Performs depth-first traversal: children are registered before parents.
        This ensures callbacks are registered in the correct order.

        Parameters
        ----------
        app : dash.Dash
            Dash application instance

        Examples
        --------
        Pseudo-code example (actual usage requires a Dash app instance).

        This method recursively registers callbacks for the template hierarchy.
        Children are registered before parents (depth-first traversal).
        """
        # Register children first (depth-first)
        for child in self.children:
            if isinstance(child, LazyComponent):
                child.register(app)

        # Then register self
        self.callbacks(app)
